In [2]:
import numpy as np

In [3]:
a =  np.array([1,4,5,4])

In [4]:
a/2

array([0.5, 2. , 2.5, 2. ])

In [5]:
data = np.random.rand(2,3,4)

In [7]:
data

array([[[0.55372609, 0.62082996, 0.06940302, 0.33901305],
        [0.0172093 , 0.39294701, 0.68539559, 0.64236089],
        [0.96245637, 0.46921203, 0.24371955, 0.47952455]],

       [[0.06203604, 0.66140137, 0.78081748, 0.91909724],
        [0.53016821, 0.74283204, 0.93163907, 0.01381522],
        [0.35228186, 0.47227326, 0.92846562, 0.70029553]]])

In [8]:
z = np.zeros((2,2,2))

In [9]:
z

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [10]:
f = np.full((2,2,2),7)

In [11]:
f

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [12]:
o = np.ones((2,2,2))

In [13]:
o

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
# basic math
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [15]:
list1

array([0.68558738, 0.2001579 , 0.35637443, 0.15426647, 0.50492342,
       0.54123497, 0.60582472, 0.98770517, 0.89491432, 0.49169091])

In [16]:
list2

array([0.61918958, 0.03838727, 0.21918174, 0.92886157, 0.86970353,
       0.87898233, 0.33131449, 0.45433717, 0.51619295, 0.53600884])

In [17]:
# basic math array operations
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mul = np.multiply(list1,list2)
dot = np.dot(list1,list2)

In [18]:
add

array([1.30477696, 0.23854518, 0.57555616, 1.08312804, 1.37462695,
       1.42021729, 0.93713922, 1.44204234, 1.41110727, 1.02769974])

In [19]:
sub

array([ 0.06639781,  0.16177063,  0.13719269, -0.77459511, -0.36478011,
       -0.33774736,  0.27451023,  0.533368  ,  0.37872138, -0.04431793])

In [20]:
div

array([1.10723341, 5.21417339, 1.62593122, 0.16608123, 0.58056959,
       0.61575182, 1.8285488 , 2.17394755, 1.73368181, 0.91731866])

In [19]:
mul

array([0.03225615, 0.38816885, 0.10391609, 0.05248753, 0.05055417,
       0.22461806, 0.33158585, 0.6031554 , 0.0007595 , 0.19335968])

In [21]:
dot

2.943433502756899

In [22]:
dot

2.943433502756899

In [26]:
#stat funstions
sqrt = np.sqrt(25)
ab = np.abs(-1)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs  = np.max(list1)

In [27]:
sqrt

5.0

In [28]:
ab

1

In [29]:
power

128