In [9]:
import numpy as np

In [11]:
a =  np.array([1,4,5,4])

In [12]:
a/2

array([0.5, 2. , 2.5, 2. ])

In [14]:
data = np.random.rand(2,3,4)

In [15]:
data

array([[[0.21675562, 0.25290502, 0.03879124, 0.61651856],
        [0.38384585, 0.81690871, 0.307541  , 0.92890789],
        [0.48318631, 0.26123806, 0.41978841, 0.74999184]],

       [[0.14940719, 0.1871922 , 0.34679733, 0.69464895],
        [0.78854706, 0.17847755, 0.95684813, 0.62614104],
        [0.45019101, 0.89487303, 0.32307602, 0.22104081]]])

In [17]:
z = np.zeros((2,2,2))

In [20]:
z

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [22]:
f = np.full((2,2,2),7)

In [23]:
f

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [24]:
o = np.ones((2,2,2))

In [28]:
o

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [30]:
# basic math
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [31]:
list1

array([0.20804133, 0.18837674, 0.01201319, 0.42727652, 0.13844607,
       0.65937904, 0.83562196, 0.39821791, 0.00308637, 0.38699446])

In [32]:
list2

array([0.78293132, 0.52713334, 0.61479104, 0.96897232, 0.03837286,
       0.66876434, 0.42226605, 0.08945909, 0.1572423 , 0.42649826])

In [38]:
# basic math array operations
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mul = np.multiply(list1,list2)
dot = np.dot(list1,list2)

In [34]:
add

array([0.99097265, 0.71551008, 0.62680423, 1.39624884, 0.17681893,
       1.32814338, 1.25788801, 0.487677  , 0.16032867, 0.81349272])

In [35]:
sub

array([-0.57488999, -0.3387566 , -0.60277784, -0.5416958 ,  0.1000732 ,
       -0.0093853 ,  0.41335592,  0.30875882, -0.15415593, -0.0395038 ])

In [36]:
div

array([0.26572105, 0.3573607 , 0.01954029, 0.44095844, 3.60791595,
       0.9859662 , 1.97889925, 4.45139689, 0.0196281 , 0.90737642])

In [37]:
mul

array([0.16288208, 0.09929966, 0.0073856 , 0.41401912, 0.00531257,
       0.44096919, 0.35285478, 0.03562421, 0.00048531, 0.16505247])

In [39]:
dot

1.6838849856244968